-- Tabla legacy sondeada por el poller (adapter/in/legacypoller). El dominio no la conoce.
CREATE TABLE legacy_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_borrador   VARCHAR(128) NOT NULL,
    payload       VARCHAR(4000),
    estado        VARCHAR(40)  NOT NULL,
    fecha_cogida  TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_legacy_request_estado ON legacy_request (estado);
